import LocalizedStrings from "react-localization";
import { localStorageKeys } from "../constants";
import http from "./http";
import chart from "./localizations/chart";
import validationErrors from "./localizations/validationErrors";
import LocalStorageService from "./LocalStorageService";

const LocalizedText = new LocalizedStrings({
  en: {
    Dashboard: "Dashboard",
    Customers: "Customers",
    Products: "Products",
    Orders: "Orders",
    Invoices: "Invoices",
    AgingReport: "Aging Report",
    PRODUCTS: "PRODUCTS",
    ORDERS: "ORDERS",
    NewCustomers: "NEW CUSTOMERS",
    TotalSales: "TOTAL SALES",
    IncomingTransfers: "INCOMING TRANSFERS",
    SeeAllProducts: "See all products",
    ViewAllOrders: "View all orders",
    SeeAllCustomers: "See all customers",
    ViewAllInvoices: "View all invoices",
    TotalRevenue: "Total Revenue",
    TotalSalesMadeToday: "Total sales made today",
    PreviousTransactionsProcessing:
      "Previous transactions processing. Last orders may not be included.",
    SalesByCategory: "Sales By Category",
    Top5SellingProducts: "Top 5 Selling Products",
    RecentOverdueInvoices: "Recent Overdue Invoices",
    ViewAgingReport: "View Aging Report",
    Invoice: "Invoice #",
    Customer: "Customer",
    Balance: "Balance",
    DueDate: "Due Date",
    Aging: "Aging(d)",
    Main: "MAIN",
    Lists: "LISTS",
    Useful: "USEFUL",
    User: "USER",
    Logout: "Logout",
    Name: "Name",
    Surname: "Surname",
    Institution: "Institution",
    Type: "Type",
    Action: "Action",
    Search: "Search...",
    AddNew: "ADD NEW",
    SKU: "SKU",
    ProductName: "Name",
    Category: "Category",
    Price: "Price",
    Date: "Date",
    TotalAmount: "Total Amount",
    OrderType: "Order Type",
    PurchaseOrder: "Purchase Order",
    Discount: "Discount",
    Freight: "Freight",
    PaymentTerms: "Payment Terms",
    PaymentStatus: "Payment Status",
    Current: "Current",
    Aging1to30Days: "1 to 30 Days",
    Aging31to60Days: "31 to 60 Days",
    Aging61to90Days: "61 to 90 Days",
    AgingOver90Days: "Over 90 Days",
    Delete: "Delete",
    Edit: "Edit",
    AreYouSure: "Are you sure?",
    DeleteCustomerMessage:
      "Do you really want to delete this customer? This process cannot be undone.",
    DeleteInvoiceMessage:
      "Do you really want to delete this invoice? This process cannot be undone.",
    DeleteOrderMessage:
      "Do you really want to delete this order? This process cannot be undone.",
    DeleteProductMessage:
      "Do you really want to delete this product? This process cannot be undone.",
    Cancel: "Cancel",
    Submit: "Submit",
    Close: "Close",
    AddNewProduct: "Add New Product",
    AddNewCustomer: "Add New Customer",
    AddNewOrder: "Add New Order",
    AddNewInvoice: "Add New Invoice",
    BillingAddress: "Billing Address",
    ShippingAddress: "Shipping Address",
    Product: "Product",
    Quantity: "Quantity",
    Add: "Add",
    Terms: "Terms",
    Status: "Status",
    ProductSaved: "The product was saved!",
    OrderSaved: "The Order was saved!",
    InvoiceSaved: "The invoice was saved!",
    CustomerSaved: "The customer was saved!",
    ProductUpdated: "The product was updated!",
    EditProduct: "Edit Product",
    CustomerUpdated: "The customer was updated!",
    EditCustomer: "Edit Customer",
    ...validationErrors.en,
    SalesChart: chart.en.salesChart,
    quantity: "quantity",
    sales: "sales",
    confirmNavigation: "Confirm Navigation",
    confirmLeavingPage:
      "Your content has not been properly saved yet! Are you sure you want to leave this page?",
    stayOnPage: "Stay on this Page",
    leavePage: "Leave this Page",
    ReferenceNumber: "Reference Number",
  },
  ro: {
    Dashboard: "Dashboard",
    Customers: "Clienți",
    Products: "Produse",
    Orders: "Comenzi",
    Invoices: "Facturi",
    AgingReport: "Raport Creanțe",
    PRODUCTS: "PRODUSE",
    ORDERS: "COMENZI",
    NewCustomers: "CLIENȚI NOI",
    TotalSales: "VÂNZĂRI TOTALE",
    IncomingTransfers: "ÎNCASĂRI",
    SeeAllProducts: "Vezi toate produsele",
    ViewAllOrders: "Vezi toate comenzile",
    SeeAllCustomers: "Vezi toți clienții",
    ViewAllInvoices: "Vezi toate facturile",
    TotalRevenue: "Venituri Totale",
    TotalSalesMadeToday: "Vânzările totale realizate astăzi",
    PreviousTransactionsProcessing:
      "Are loc procesarea tranzacțiilor anterioare. Ultimele comenzi pot să nu fie incluse.",
    SalesByCategory: "Vânzări pe Categorii de Produs",
    Top5SellingProducts: "Top 5 Produse Vândute",
    RecentOverdueInvoices: "Facturi Restante Recente",
    ViewAgingReport: "Vezi Raportul Creanțe",
    Invoice: "Factura #",
    Customer: "Client",
    Balance: "Suma",
    DueDate: "Data Scadentă",
    Aging: "Vechime(z)",
    Main: "MAIN",
    Lists: "LISTE",
    Useful: "UTIL",
    User: "USER",
    Logout: "Logout",
    Name: "Prenume",
    Surname: "Nume",
    Institution: "Instituţie",
    Type: "Tip",
    Action: "Acțiune",
    Search: "Search...",
    AddNew: "ADAUGĂ",
    SKU: "SKU",
    ProductName: "Denumire",
    Category: "Categorie",
    Price: "Preț",
    Date: "Data",
    TotalAmount: "Suma Totală",
    OrderType: "Tipul Comenzii",
    PurchaseOrder: "Comanda de Achiziție",
    Discount: "Reducere",
    Freight: "Suma de Livrare",
    PaymentTerms: "Termen de Plată",
    PaymentStatus: "Statut de Plată",
    Current: "Sold Curent",
    Aging1to30Days: "1 până la 30 de zile",
    Aging31to60Days: "31 până la 60 de zile",
    Aging61to90Days: "61 până la 90 de zile",
    AgingOver90Days: "Peste 90 de zile",
    Delete: "Șterge",
    Edit: "Editați",
    AreYouSure: "Ești sigur?",
    DeleteCustomerMessage:
      "Chiar doriți să ștergeți acest client? Acest proces nu poate fi anulat.",
    DeleteInvoiceMessage:
      "Chiar doriți să ștergeți această factură? Acest proces nu poate fi anulat.",
    DeleteOrderMessage:
      "Chiar doriți să ștergeți această comandă? Acest proces nu poate fi anulat.",
    DeleteProductMessage:
      "Chiar doriți să ștergeți acest produs? Acest proces nu poate fi anulat.",
    Cancel: "Anulare",
    Submit: "Trimite",
    Close: "Închide",
    AddNewProduct: "Adăugați un Produs Nou",
    AddNewCustomer: "Adăugați un Client Nou",
    AddNewOrder: "Adăugați o Comandă Nouă",
    AddNewInvoice: "Adăugați o Nouă Factură",
    BillingAddress: "Adresa de Facturare",
    ShippingAddress: "Adresa de Transport",
    Product: "Produs",
    Quantity: "Cantitate",
    Add: "Adaugă",
    Terms: "Termen",
    Status: "Statut",
    ProductSaved: "Produsul a fost salvat!",
    OrderSaved: "Comanda a fost salvată!",
    InvoiceSaved: "Factura a fost salvată!",
    CustomerSaved: "Clientul a fost salvat!",
    ProductUpdated: "Produsul a fost actualizat!",
    EditProduct: "Editați Produsul",
    CustomerUpdated: "Clientul a fost actualizat!",
    EditCustomer: "Editați clientul",
    ...validationErrors.ro,
    SalesChart: chart.ro.salesChart,
    quantity: "cantitate",
    sales: "vânzări",
    confirmNavigation: "Confirmați Navigarea",
    confirmLeavingPage:
      "Conținutul dvs. nu a fost salvat! Sigur doriți să părăsiți această pagină?",
    stayOnPage: "Rămân pe această pagină",
    leavePage: "Părăsesc această pagină",
    ReferenceNumber: "Numărul de referință",
  },
  it: {
    Dashboard: "Dashboard",
    Customers: "Clienti",
    Products: "Prodotti",
    Orders: "Ordini",
    Invoices: "Fatture",
    AgingReport: "Rapporto Debito",
    PRODUCTS: "PRODOTTI",
    ORDERS: "ORDINI",
    NewCustomers: "NUOVI CLIENTI",
    TotalSales: "VENDITE TOTALI",
    IncomingTransfers: "PROVENTO",
    SeeAllProducts: "Vedi tutti i prodotti",
    ViewAllOrders: "Vedi tutti gli ordini",
    SeeAllCustomers: "Vedi tutti i clienti",
    ViewAllInvoices: "Vedi tutte le fatture",
    TotalRevenue: "Entrate Totali",
    TotalSalesMadeToday: "Vendite totali effettuate oggi",
    PreviousTransactionsProcessing:
      "Elaborazione di transazioni precedenti. Gli ultimi ordini potrebbero non essere inclusi.",
    SalesByCategory: "Vendite per Categoria di Prodotto",
    Top5SellingProducts: "I 5 prodotti più venduti",
    RecentOverdueInvoices: "Fattori Restante Recente",
    ViewAgingReport: "Vedi Rapporto Debito",
    Invoice: "Fattura #",
    Customer: "Cliente",
    Balance: "Quantità",
    DueDate: "Scadenza",
    Aging: "Invecchiamento(g)",
    Main: "PRINCIPALE",
    Lists: "LISTE",
    Useful: "UTILE",
    User: "UTENTE",
    Logout: "Disconnettersi",
    Name: "Nome",
    Surname: "Cognome",
    Institution: "Istituzione",
    Type: "Genere",
    Action: "Azione",
    Search: "Ricerca...",
    AddNew: "AGGIUNGERE NUOVA",
    SKU: "SKU",
    ProductName: "Nome",
    Category: "Categoria",
    Price: "Prezzo",
    Date: "Data",
    TotalAmount: "Importo totale",
    OrderType: "Tipo di Ordine",
    PurchaseOrder: "Ordinazione d'acquisto",
    Discount: "Sconto",
    Freight: "Importo di Spedizione",
    PaymentTerms: "Termini di Pagamento",
    PaymentStatus: "Stato del Pagamento",
    Current: "Bilancio Corrente",
    Aging1to30Days: "Da 1 a 30 Giorni",
    Aging31to60Days: "Da 31 a 60 Giorni",
    Aging61to90Days: "Da 61 a 90 Giorni",
    AgingOver90Days: "Oltre 90 Giorni",
    Delete: "Elimina",
    Edit: "Modificare",
    AreYouSure: "Sei sicuro?",
    DeleteCustomerMessage:
      "Vuoi davvero eliminare questo cliente? Questo processo non può essere annullato.",
    DeleteInvoiceMessage:
      "Vuoi davvero eliminare questa fattura? Questo processo non può essere annullato.",
    DeleteOrderMessage:
      "Vuoi davvero eliminare questo ordine? Questo processo non può essere annullato.",
    DeleteProductMessage:
      "Vuoi davvero eliminare questo prodotto? Questo processo non può essere annullato.",
    Cancel: "Annulla",
    Submit: "Invia",
    Close: "Chiudere",
    AddNewProduct: "Aggiungi Nuovo Prodotto",
    AddNewCustomer: "Aggiungi Nuovo Cliente",
    AddNewOrder: "Aggiungi Nuovo Ordine",
    AddNewInvoice: "Aggiungi Nuova Fattura",
    BillingAddress: "Indirizzo Di Fatturazione",
    ShippingAddress: "Indirizzo Di Spedizione",
    Product: "Prodotto",
    Quantity: "Quantità",
    Add: "Aggiungere",
    Terms: "Termini",
    Status: "Stato",
    ProductSaved: "Il prodotto è stato salvato!",
    OrderSaved: "L'ordine è stato salvato!",
    InvoiceSaved: "La fattura è stata salvata!",
    CustomerSaved: "Il cliente è stato salvato!",
    ProductUpdated: "Il prodotto è stato aggiornato!",
    EditProduct: "Modifica Prodotto",
    CustomerUpdated: "Il cliente è stato aggiornato!",
    EditCustomer: "Modifica Cliente",
    ...validationErrors.it,
    SalesChart: chart.it.salesChart,
    quantity: "quantità",
    sales: "i saldi",
    confirmNavigation: "Conferma Navigazione",
    confirmLeavingPage:
      "Il tuo contenuto non è stato ancora salvato correttamente! Sei sicuro di voler lasciare questa pagina?",
    stayOnPage: "Rimanere su questa pagina",
    leavePage: "Lascia questa pagina",
    ReferenceNumber: "Numero di Riferimento",
  },
});

setLanguage(LocalStorageService.getItem(localStorageKeys.language) ?? "en");

export function setLanguage(countryCode: string) {
  LocalStorageService.setItem(localStorageKeys.language, countryCode);
  LocalizedText.setLanguage(countryCode);
  http.setLanguage(countryCode);
}

export default LocalizedText;
